### ISSUE TITLE
require('phaser') breaks browserify

### ISSUE THREAD

**Issue by tdboone** [tdboone/phaser-template#1]
We can't simply use `require('phaser')` to use the Phaser library. See the discussion here:
https://github.com/photonstorm/phaser/issues/1186

I added the browserify-shim as suggested by woutercommandeur, but I'm getting `Error: Cannot find module 'nw.gui'`. I'm still trying to figure out a work-around to get this working.

**Comment by zpchavez** [comment]
I got it to work last week. The trick was to load phaser.js using script tags and then create a dummy phaser.js file with: `module.exports = Window.Phaser;`. I'll try to add it to your template.

**Comment by tdboone** [comment]
Awesome, thanks! FYI, I forgot to add something in the gulp build task to copy an index.html from the application into the build folder, so you'll need to do that first to try to run anything. Also, that PR I made (#2) is probably a garbage dead-end, so feel free to disregard it.

**Comment by zpchavez** [comment]
Pushed my branch. You'll just do `gulp` instead of `gulp watch` to start it. Live reload doesn't seem to work. Don't know why.

**Comment by tdboone** [comment]
Fixed (for now) by #3
